name = "swell"
version = "1.0.1"
description = "ğŸŒŠ A GraphQL implementation in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bigmoves", repo = "swell" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.0.0 and < 2.0.0"
